# Generated by Django 5.2.5 on 2025-08-19 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Record',
            new_name='Records',
        ),
    ]
